# numpy 연산


+ abs / fabs : 절대값
+ sqrt	: 제곱근
+ square	: 제곱
+ exp	 : 지수
+ ceil / floor : 소수자릿수 올림/내림
+ rint	:소수자릿수 반올림
+ modf	: 원소의 몫과 나머지를 각 배열로 변환
+ lsnan	: 각 원소가 Nan인지 아닌지 불린 배열로 리턴

+ add / subtract	: 두 배열의 같은 위치의 요소끼리 덧셈/뺄셈
+ multiply	: 배열 원소끼리 곱셉
+ divide	: 첫번째 배열의 원소에서 두번째 배열 원소로 나눔
+ power	: 첫번째 배열의 원소에 두번째 배열의 원소만큼 제곱
+ maximum	: 비교하는 두 원소 중 큰 값
+ mod	: 첫번째 배열의 원소에서 두번째 배열 원소로 나눈 나머지



###  선형대수 연산

In [3]:
import numpy as np

# (1) 배열의 연산
arr1 = np.array([[1,2,3]
                 ,[4,5,6]])
arr2 = np.array([[1,1,1]
                 ,[2,2,2]])


print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)   # 행렬의 연산이 아님. 각 요소의 곱
print(arr1 ** arr2)  # 행렬의 연산은 
print(arr1 / arr2)
print(arr1 // arr2)
print(arr1 % arr2)

[[2 3 4]
 [6 7 8]]
[[0 1 2]
 [2 3 4]]
[[ 1  2  3]
 [ 8 10 12]]
[[1.  2.  3. ]
 [2.  2.5 3. ]]
[[1 2 3]
 [2 2 3]]
[[0 0 0]
 [0 1 0]]


In [7]:
# (2) 행렬의 곱

A = np.array(
    [[1, 2, 3],
    [4, 5, 6]])
B = np.array(
    [[7,8],
     [9,10],
     [11, 12]])

np.dot(A,B)

array([[ 58,  64],
       [139, 154]])

In [9]:
# (3) 전치행렬
#       - 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
A = np.array(
    [[1, 2, 3],
    [4, 5, 6]])

np.transpose(A) # 2-3 -> 3-2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
print(A)
print(np.transpose(A))
print(A.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


### 넘파이 통계 함수

+ sum	: 배열 원소들의 합
+ mean :산술 평균
+ std / var	: 표준편차 / 분산
+ min / max	: 최소 값 / 최대 값
+ cumsum	: 각 원소의 누적값
+ cumprod	: 각 원소의 누적곱


In [14]:
import numpy as np

ar = np.array([1,3,5,7])

In [15]:
# 평균
np.mean(ar)

4.0

In [16]:
# 총합
np.sum(ar)

16

In [18]:
# 큰값
np.max(ar)

7

In [17]:
# 각 원소의 누적곱
np.cumprod(ar)

array([  1,   3,  15, 105])

#### 2차원 배열에서

In [19]:
# 2차원 배열을 arr 생성
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# 총합
np.sum(arr)

#  특정 행의 합
np.sum(arr[1])
# axis=0 : 행방향 - 열단위 합
hang = np.sum(arr, axis=0)
print(hang)
# axis=1 : 열방향 - 행단위 합
np.sum(arr, axis=1)

[5 7 9]


array([ 6, 15])

In [27]:
# 불린 배열에서의 배열 : 조건을 넣어 ture, false
arr2 = np.array([[12, 7, 22], [20,33, 44], [4,5,6]])
arr2

arr2[arr2 > 20] # 20 이상인 애들만 true로 새로 추출

array([22, 33, 44])

In [30]:
# unique 연산자를 이용하여 중복제거
region = np.array(['가산','서울','서울','판교','가산'])
region
np.unique(region)

array(['가산', '서울', '판교'], dtype='<U2')

### 행렬의 정렬 

In [33]:
arr = np.array([9,3,6,1,7,2,4,8,5,6])
arr

np.sort(arr) # 원래 배열을 바꾸지않는다.
np.sort(arr)[::-1]

array([9, 8, 7, 6, 6, 5, 4, 3, 2, 1])

In [36]:
arr2 = np.array([[9,3,6],
                 [1,7,2],
                 [4,8,5]])
arr2

np.sort(arr2) # each list sort
np.sort(arr2,axis=0) # compare arr2[0] value in each list
np.sort(arr2,axis=1) # same with first

array([[3, 6, 9],
       [1, 2, 7],
       [4, 5, 8]])